apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-kata
          image: wilsonianbcoil/kata-deploy:kustomize
